# Generated by Django 5.1.3 on 2025-05-27 08:21

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
